spring:
  profiles:
    active: build-frontend
  application:
    name: jumbleapplication
  datasource:
    url: jdbc:postgresql://localhost:5432/jumbledb
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update

server:
  error:
    include-message: always
    include-binding-errors: always

nbrownie:
  jumbleapplication:
      jwtSecret: mysecret
      jwtExpirationMs: 86400000


#cloud:
#  aws:
#    credentials:
#      instanceProfile: false
#      useDefaultAwsCredentialsChain: false
#      profileName: nbrownie
#
#    s3:
#      default-bucket:
#      multipart.maxFileSize: 5MB
#      multipart.maxRequestSize: 5MB
#    region:
#      static: eu-central-1
#      auto: false
#


mapbox-client:
  access-token: pk.eyJ1IjoibmJyb3duaWUiLCJhIjoiY2t4YTgzdHFwMGVzbDJwbXduamIwcjVobyJ9.1dvOHUtZhQCG2BBl7rkjtg