spring:
  profiles:
    active: build-frontend
  application:
    name: jumbleapplication
  datasource:
    url: jdbc:postgresql://localhost:5432/jumbledb
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update

#  data:
#    rest:
#      base-path: /api

server:
  error:
    include-message: always
    include-binding-errors: always

#  servlet:
#    context-path: "/"
#  error:
#    include-message: always
cloud:
  aws:
    credentials:
      instanceProfile: false
      useDefaultAwsCredentialsChain: false
      profileName: nbrownie

    s3:
      default-bucket:
      multipart.maxFileSize: 5MB
      multipart.maxRequestSize: 5MB
    region:
      static: eu-central-1
      auto: false
#security:
#  jwt:
#    secret: ${JWT-SECRET}
#    expiresAfterMinutes: 30
#
mapbox-client:
  access-token: pk.eyJ1IjoibmJyb3duaWUiLCJhIjoiY2t1aWVhNGhlMDJrZjMwcXoyZWUybDYxZCJ9.HLXmIOmvZtR3uhDR1JofjA